### ISSUE TITLE
Unable to get batchspawner working

### ISSUE THREAD

**Issue by chandag** [jupyterhub/batchspawner#150]
Trying a set up where we would have JupyterHub configured on host XX.XX.XX.XX and want to use batchspawner to spawn single user notebooks on host YY.YY.YY.YY
But the spawn is failing with below error and hence unable to progress.
jupyterhub_config.py file and the execution log generated by executing jupyterhub with --debug has been uploaded here.

Please guide as it seems I'm doing something fundamentally wrong here!

ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /usr/local/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
  File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
    await spawn_future
  File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 642, in spawn
    raise e
  File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 546, in spawn
    url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.6/site-packages/batchspawner/batchspawner.py", line 320, in start
    assert self.state_ispending()
	
Also, there is no clear documentation available to set this up, so if this can kindly be looked at or if someone can kindly share any guide to implement this set-up that will be really helpful.

**Comment by Hoeze** [comment]
Hi, I'd like to give you some hints which helped me to get it running:
1) add `import batchspawner` in your config file
2) you can look at the job logs to find out more about the problem (seems like your job does not connect to jupyterhub)

**Comment by rkdarst** [comment]
You can see this for some debugging hints I recently wrote: https://github.com/jupyterhub/batchspawner/pull/151/files

Do you see any relevant messages in any of those places?
