### ISSUE TITLE
Command 'None' returned non-zero exit status 1

### ISSUE THREAD

**Issue by iagomez** [jupyterhub/batchspawner#18]
Hello everyone,

I'm having trouble figuring out what could be causing this issue, but hopefully this is something you have seen before or can give me towards some rabbit holes I can go jump in.

Right before the command is submitted I can see in the output `Spawner submitting job using sudo -E -u igomez bsub`, which means `cmd` is set to ` sudo -E -u igomez bsub`. However, for some reason I'm getting an error `subprocess.CalledProcessError: Command 'None' returned non-zero exit status 1`

What makes this particularly interesting is that this was working perfectly fine, and if I kill jupyterhub and launch it again it works. But it looks like eventually it gets stuck in this state and I can no longer spawn single-user notebooks.

**My setup is:**
* OS: RHEL 7
* jupyterhub --version 0.6.1
* batchspawner forked at git ref: bec4cdf8de13d436b0cc22665358b8143fe1edf7 installed with `pip -e`

```
[I 2016-10-10 09:56:55.635 JupyterHub batchspawner:160] Spawner submitting job using sudo -E -u igomez bsub
[I 2016-10-10 09:56:55.636 JupyterHub batchspawner:161] Spawner submitted script:
    #!/bin/bash
    #BSUB -J Jupyterhub-Spawner
    #BSUB -q normal
    #BSUB -e /temp_test/jupyter-hub.err
    #BSUB -o /temp_test/jupyter-hub.out

    export PATH=/gpfs/grid/anaconda/python3/bin:$PATH
    jupyterhub-singleuser --user=igomez --port=57267 --cookie-name=jupyter-hub-token-igomez --base-url=/user/igomez --hub-host= --hub-prefix=/hub/ --hub-api-url=http://10.102.10.162:8081/hub/api --ip=0.0.0.0 --notebook-dir=~

[E 2016-10-10 09:56:55.655 JupyterHub user:237] Unhandled error starting igomez's server: Command 'None' returned non-zero exit status 1
[E 2016-10-10 09:56:55.669 JupyterHub web:1524] Uncaught exception POST /hub/login?next=%2Fhub%2Fuser%2Figomez (10.102.10.162)
    HTTPServerRequest(protocol='http', host='gridnode3:8000', method='POST', uri='/hub/login?next=%2Fhub%2Fuser%2Figomez', version='HTTP/1.1', remote_ip='10.102.10.162', headers={'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Referer': 'http://gridnode3:8000/hub/login?next=%2Fhub%2Fuser%2Figomez', 'Origin': 'http://gridnode3:8000', 'Upgrade-Insecure-Requests': '1', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'close', 'Host': 'gridnode3:8000', 'Content-Length': '36', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/gpfs/grid/anaconda/python3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/gpfs/grid/anaconda/python3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 79, in post
        yield self.spawn_single_user(user)
      File "/gpfs/grid/anaconda/python3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/gpfs/grid/anaconda/python3/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/gpfs/grid/anaconda/python3/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/gpfs/grid/anaconda/python3/batchspawner/batchspawner/batchspawner.py", line 271, in start
        job = yield self.submit_batch_script()
      File "/gpfs/grid/anaconda/python3/batchspawner/batchspawner/batchspawner.py", line 162, in submit_batch_script
        out = yield run_command(cmd, input=script, env=self.get_env())
      File "/gpfs/grid/anaconda/python3/batchspawner/batchspawner/batchspawner.py", line 52, in run_command
        err = yield proc.wait_for_exit()
    subprocess.CalledProcessError: Command 'None' returned non-zero exit status 1
```

**Comment by willingc** [comment]
@minrk Ideas? Perhaps trying jupyterhub master?

**Comment by minrk** [comment]
Might want to check `cmd` in run_command. It seems the first item in that is None for some reason.

**Comment by iagomez** [comment]
I added print statements to collect cmd inside run_command and after Subprocess is instantiated. It's been working fine for the past couple of days without making any changes. If you'd like we can close this issue for now and I'll update it with new information if it happens again

**Comment by iagomez** [comment]
Hey everyone,

I think I figured this out. I redirected the stdout and stderr to files and I found this golden nugget:

```

[I 2016-10-17 10:15:14.713 JupyterHub batchspawner:162] Spawner submitting job using sudo -E -u igomez bsub
[I 2016-10-17 10:15:14.714 JupyterHub batchspawner:163] Spawner submitted script:
    #!/bin/bash
    #BSUB -J Jupyterhub-Spawner
    #BSUB -q normal
    #BSUB -e /gpfs/work/temp_test/jupyter-hub.err
    #BSUB -o /gpfs/work/temp_test/jupyter-hub.out

    export PATH=/gpfs/grid/anaconda/python3/bin:$PATH
    jupyterhub-singleuser --user=igomez --port=60508 --cookie-name=jupyter-hub-token-igomez --base-url=/user/igomez --hub-host= --hub-prefix=/hub/ --hub-api-url=http://10.102.10.162:8081/hub/api --ip=0.0.0.0 --notebook-dir=~

sudo: sorry, you must have a tty to run sudo
[E 2016-10-17 10:15:14.732 JupyterHub user:237] Unhandled error starting igomez's server: Command 'None' returned non-zero exit status 1
[E 2016-10-17 10:15:14.748 JupyterHub web:1524] Uncaught exception POST /hub/login?next=%2Fhub%2Fhome (10.102.10.162)
```
**sudo: sorry, you must have a tty to run sudo**

I'm running RHEL 7 which by default apparently requires a tty for sudo. Now it even works with systemd which I had not been able to get it to work before.

Cheers.

**Comment by willingc** [comment]
That's great @iagomez. FYI, there's also a systemdspawner now that @yuvipanda worked on :smile:
