### ISSUE TITLE
Failed to connect to hub api

### ISSUE THREAD

**Issue by miguelmarco** [jupyterhub/batchspawner#63]
I am trying to setup a jupyterhub server in a slurm cluster.

It has the following nodes:

- **nodo00**: the one that runs the jupyterhub instance, and the only one that is exposed to the internet

- **nodo01, nodo02 and nodo03** the actual computing nodes.

I have tried to set it up with the batchspawner but when I try to start a new server,  I get the following error message in the web browser:

```
Failed to connect to Hub API at 'http://127.0.0.1:8081/hub/api'.  Is the Hub accessible at this URL (from host: nodo03)?  Make sure to set c.JupyterHub.hub_ip to an IP accessible to single-user servers if the servers are not on the same host as the Hub.
```

The log of jupyterhub says the following:

```
[I 2018-04-07 18:03:43.003 JupyterHub app:834] Loading cookie_secret from /root/jupyterhub_cookie_secret
[W 2018-04-07 18:03:43.017 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-04-07 18:03:43.017 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-04-07 18:03:43.017 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[I 2018-04-07 18:03:43.046 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-04-07 18:03:43.047 JupyterHub proxy:415] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2018-04-07 18:03:43.047 JupyterHub proxy:458] Starting proxy @ https://*:443/
18:03:43.151 - info: [ConfigProxy] Proxying https://*:443 to (no default)
18:03:43.153 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
18:03:43.222 - info: [ConfigProxy] 200 GET /api/routes 
[W 2018-04-07 18:03:43.222 JupyterHub proxy:304] Adding missing default route
[I 2018-04-07 18:03:43.222 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
18:03:43.228 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
18:03:43.229 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2018-04-07 18:03:43.230 JupyterHub app:1581] JupyterHub is now running at https://:443/
[I 2018-04-07 18:04:02.063 JupyterHub log:122] 302 GET / → /hub (@::ffff:188.79.184.88) 1.82ms
[I 2018-04-07 18:04:02.304 JupyterHub log:122] 302 GET /hub → /hub/login (@::ffff:188.79.184.88) 0.54ms
[I 2018-04-07 18:04:02.527 JupyterHub log:122] 200 GET /hub/login (@::ffff:188.79.184.88) 24.44ms
[I 2018-04-07 18:04:11.561 JupyterHub base:346] User logged in: mmarco
[I 2018-04-07 18:04:11.562 JupyterHub log:122] 302 POST /hub/login?next= → /hub/ (@::ffff:188.79.184.88) 24.12ms
[I 2018-04-07 18:04:11.834 JupyterHub log:122] 302 GET /hub/ → /hub/home (mmarco@::ffff:188.79.184.88) 6.23ms
[I 2018-04-07 18:04:12.097 JupyterHub log:122] 200 GET /hub/home (mmarco@::ffff:188.79.184.88) 9.89ms
[I 2018-04-07 18:04:13.936 JupyterHub log:122] 200 GET /hub/spawn (mmarco@::ffff:188.79.184.88) 10.31ms
[I 2018-04-07 18:04:16.200 JupyterHub batchspawner:177] Spawner submitting job using sudo -E -u mmarco sbatch --parsable
[I 2018-04-07 18:04:16.200 JupyterHub batchspawner:178] Spawner submitted script:
    #!/bin/bash
    #SBATCH --partition=ALL
    #SBATCH --time=8:00:00
    #SBATCH --output=/home/mmarco/jupyterhub_slurmspawner_%j.log
    #SBATCH --job-name=spawner-jupyterhub
    #SBATCH --workdir=/home/mmarco
    #SBATCH --mem=4gb
    #SBATCH --export=PATH,JUPYTERHUB_BASE_URL,LANG,JUPYTERHUB_API_URL,SHELL,USER,JUPYTERHUB_OAUTH_CALLBACK_URL,JUPYTERHUB_CLIENT_ID,JUPYTERHUB_SERVICE_PREFIX,JUPYTERHUB_API_TOKEN,JPY_API_TOKEN,JUPYTERHUB_USER,HOME,JUPYTERHUB_HOST
    #SBATCH --uid=mmarco
    #SBATCH --get-user-env=L
    #SBATCH 
    
    which jupyterhub-singleuser
    jupyterhub-singleuser --ip="0.0.0.0" --port=48132
    
[I 2018-04-07 18:04:16.212 JupyterHub batchspawner:181] Job submitted. cmd: sudo -E -u mmarco sbatch --parsable output: 383
[I 2018-04-07 18:04:16.746 JupyterHub batchspawner:319] Notebook server job 383 started at nodo03:48132
[I 2018-04-07 18:04:17.423 JupyterHub base:447] User mmarco took 1.526 seconds to start
[I 2018-04-07 18:04:17.426 JupyterHub proxy:231] Adding user mmarco to proxy /user/mmarco/ => http://nodo03:48132
18:04:17.428 - info: [ConfigProxy] Adding route /user/mmarco -> http://nodo03:48132
18:04:17.429 - info: [ConfigProxy] 201 POST /api/routes/user/mmarco 
[I 2018-04-07 18:04:17.434 JupyterHub log:122] 302 POST /hub/spawn → /user/mmarco/ (mmarco@::ffff:188.79.184.88) 1541.85ms
[I 2018-04-07 18:04:18.302 JupyterHub log:122] 302 GET /hub/api/oauth2/authorize?redirect_uri=%2Fuser%2Fmmarco%2Foauth_callback&client_id=user-mmarco&response_type=code&state=eyJuZXh0X3VybCI6ICIvdXNlci9tbWFyY28vdHJlZT8iLCAidXVpZCI6ICJkZjcyOTQ1ZWI2MTM0YzVmODcwMmExZDJjNzI4ZjQ1YiJ9 → /user/mmarco/oauth_callback?code=dcb7d6a3-06ee-4223-a20f-cfa7d17c2226&state=eyJuZXh0X3VybCI6ICIvdXNlci9tbWFyY28vdHJlZT8iLCAidXVpZCI6ICJkZjcyOTQ1ZWI2MTM0YzVmODcwMmExZDJjNzI4ZjQ1YiJ9 (mmarco@::ffff:188.79.184.88) 81.81ms
[W 2018-04-07 18:05:16.770 JupyterHub base:517] User mmarco server stopped, with exit code: 1
[I 2018-04-07 18:05:16.771 JupyterHub proxy:254] Removing user mmarco from proxy (/user/mmarco/)
18:05:16.774 - info: [ConfigProxy] Removing route /user/mmarco
18:05:16.775 - info: [ConfigProxy] 204 DELETE /api/routes/user/mmarco 
18:08:43.236 - info: [ConfigProxy] 200 GET /api/routes 
```

Finally, the log file of the job says: 

```
jupyterhub_slurmspawner_380.log  jupyterhub_slurmspawner_382.log  
jupyterhub_slurmspawner_381.log  jupyterhub_slurmspawner_383.log  
[root@nodo00 ~]# more /home/mmarco/jupyterhub_slurmspawner_383.log 
/bin/jupyterhub-singleuser
[I 2018-04-07 18:04:17.292 SingleUserNotebookApp extension:53] JupyterLab beta preview extension loaded from /usr/lib/python3.4/si
te-packages/jupyterlab
[I 2018-04-07 18:04:17.292 SingleUserNotebookApp extension:54] JupyterLab application directory is /usr/share/jupyter/lab
[I 2018-04-07 18:04:17.297 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
[E 2018-04-07 18:04:17.300 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://127.0.0.1:8081/hub/api (att
empt 1/5). Is it running?
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib64/python3.4/asyncio/futures.py", line 274, in result
        raise self._exception
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2018-04-07 18:04:17.419 SingleUserNotebookApp log:122] 302 GET /user/mmarco/ → /user/mmarco/tree? (@192.168.2.10) 1.35ms
[I 2018-04-07 18:04:17.699 SingleUserNotebookApp log:122] 302 GET /user/mmarco/ → /user/mmarco/tree? (@::ffff:188.79.184.88) 1.03m
s
[I 2018-04-07 18:04:17.959 SingleUserNotebookApp log:122] 302 GET /user/mmarco/tree? → /hub/api/oauth2/authorize?redirect_uri=%2Fu
ser%2Fmmarco%2Foauth_callback&client_id=user-mmarco&response_type=code&state=eyJuZXh0X3VybCI6ICIvdXNlci9tbWFyY28vdHJlZT8iLCAidXVpZ
CI6ICJkZjcyOTQ1ZWI2MTM0YzVmODcwMmExZDJjNzI4ZjQ1YiJ9 (@::ffff:188.79.184.88) 5.45ms
[E 2018-04-07 18:04:18.556 SingleUserNotebookApp auth:249] Error connecting to http://127.0.0.1:8081/hub/api: HTTPConnectionPool(h
ost='127.0.0.1', port=8081): Max retries exceeded with url: /hub/api/oauth2/token (Caused by NewConnectionError('<urllib3.connecti
on.HTTPConnection object at 0x2b6e9f622908>: Failed to establish a new connection: [Errno 111] Connection refused',))
[W 2018-04-07 18:04:18.556 SingleUserNotebookApp web:1618] 500 GET /user/mmarco/oauth_callback?code=dcb7d6a3-06ee-4223-a20f-cfa7d1
7c2226&state=eyJuZXh0X3VybCI6ICIvdXNlci9tbWFyY28vdHJlZT8iLCAidXVpZCI6ICJkZjcyOTQ1ZWI2MTM0YzVmODcwMmExZDJjNzI4ZjQ1YiJ9 (::ffff:188.
79.184.88): Failed to connect to Hub API at 'http://127.0.0.1:8081/hub/api'.  Is the Hub accessible at this URL (from host: nodo03
)?  Make sure to set c.JupyterHub.hub_ip to an IP accessible to single-user servers if the servers are not on the same host as the
 Hub.
[E 2018-04-07 18:04:18.615 SingleUserNotebookApp log:114] {
      "Cookie": "user-mmarco-oauth-state=\"2|1:0|10:1523117057|23:user-mmarco-oauth-state|140:ZXlKdVpYaDBYM1Z5YkNJNklDSXZkWE5sY2k5
dGJXRnlZMjh2ZEhKbFpUOGlMQ0FpZFhWcFpDSTZJQ0prWmpjeU9UUTFaV0kyTVRNMFl6Vm1PRGN3TW1FeFpESmpOekk0WmpRMVlpSjk=|8beec7a37a57e5139f5f8898a
b06ef030ce43d131d77f56155be158495af89a3\"",
      "Dnt": "1",
      "X-Forwarded-Proto": "https",
      "Accept-Language": "es-ES,es;q=0.9",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.148 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Referer": "https://gauss.unizar.es/hub/spawn",
      "Host": "gauss.unizar.es",
      "Accept-Encoding": "gzip, deflate, br",
      "Connection": "close",
      "X-Forwarded-Host": "gauss.unizar.es",
      "Cache-Control": "max-age=0",
      "Upgrade-Insecure-Requests": "1",
      "X-Forwarded-For": "::ffff:188.79.184.88",
      "X-Forwarded-Port": "443"
    }
[E 2018-04-07 18:04:18.615 SingleUserNotebookApp log:122] 500 GET /user/mmarco/oauth_callback?code=dcb7d6a3-06ee-4223-a20f-cfa7d17
c2226&state=eyJuZXh0X3VybCI6ICIvdXNlci9tbWFyY28vdHJlZT8iLCAidXVpZCI6ICJkZjcyOTQ1ZWI2MTM0YzVmODcwMmExZDJjNzI4ZjQ1YiJ9 (@::ffff:188.
79.184.88) 67.53ms
[E 2018-04-07 18:04:19.305 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://127.0.0.1:8081/hub/api (att
empt 2/5). Is it running?
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib64/python3.4/asyncio/futures.py", line 274, in result
        raise self._exception
    ConnectionRefusedError: [Errno 111] Connection refused
[E 2018-04-07 18:04:23.312 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://127.0.0.1:8081/hub/api (att
empt 3/5). Is it running?
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib64/python3.4/asyncio/futures.py", line 274, in result
        raise self._exception
    ConnectionRefusedError: [Errno 111] Connection refused
[E 2018-04-07 18:04:31.325 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://127.0.0.1:8081/hub/api (att
empt 4/5). Is it running?
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib64/python3.4/asyncio/futures.py", line 274, in result
        raise self._exception
    ConnectionRefusedError: [Errno 111] Connection refused
[E 2018-04-07 18:04:47.345 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://127.0.0.1:8081/hub/api (att
empt 5/5). Is it running?
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib64/python3.4/asyncio/futures.py", line 274, in result
        raise self._exception
    ConnectionRefusedError: [Errno 111] Connection refused
```

It seems that somehow there is no connection with the process that is running in the computing node. Any clue about how to proceed?

**Comment by mbmilligan** [comment]
Hi @miguelmarco -

Like it says in the error message, `c.JupyterHub.hub_ip` needs to be set in your config file to the IP address where the compute nodes can connect to the Hub node. This might be as simple as setting `c.JupyterHub.hub_ip = nodo00` but if the Hub node has an IP address on the internal network you may need to use that. If there is only the single IP address you probably want to set up a firewall rule ensuring that the Hub API port isn't accessible to the public internet.

**Comment by miguelmarco** [comment]
Thanks, it worked.
