### ISSUE TITLE
Permission denied when spawning job using slurm

### ISSUE THREAD

**Issue by djevo1** [jupyterhub/batchspawner#68]
Attempting to use the slurm batch spawner results in the following error. I have tried unsetting the XDG_RUNTIME_DIR as some have suggested but this doesn't appear to work. It is odd because the user that is executing the slurm command via sudo has permissions to the directory listed below. This happens for all users.

```
Traceback (most recent call last):
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/web_services/galaxy/jupyter_conda/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1505, in initialize
    self.init_configurables()
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1209, in init_configurables
    connection_dir=self.runtime_dir,
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/user/1261'
```

**Comment by willingc** [comment]
Hi @djevo1, I wonder if you are running up against the first bullet in this section: https://github.com/jupyterhub/batchspawner#v08-compatible-with-jupyterhub-050-through-08109dev

**Comment by djevo1** [comment]
Possibly, Although I am using the default Slurm batch file. I could try
adding that as jupyterhub is definitely using audio to run as the real user.

**Comment by djevo1** [comment]
Attempted using the uid flag with sbatch but am getting the same error. Slurm is version 15.0.13

```
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/web_services/galaxy/jupyter_conda/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1505, in initialize
    self.init_configurables()
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1209, in init_configurables
    connection_dir=self.runtime_dir,
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/var/web_services/galaxy/jupyter_conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/user/1261'
```

**Comment by rkdarst** [comment]
This looks like the `$XDG_RUNTIME_DIR` thing to me.  How are you unsetting it?

```
batch_cmd="""\
unset XDG_RUNTIME_DIR
<old jupyterhub-singleuser command here with my own options>"""
```
Then use `cmd=batch_cmd` on my spawner instance (and can check the jupyterhub logs to make sure it substituted properly). (this is hacking `cmd` to a multiline thing so I don't have to replace the whole batch script, but could also be put directly in the batch script if you are editing that).  The key line is `unset XDG_RUNTIME_DIR`.  I guess there are many ways this can be re-set in the layers of sudo, bash startup, and slurm `--get-user-env`, likely from the last one.

When debugging slurm stuff, I will usually run `srun {other slurm options} --pty bash` to get an interactive shell to check the environment to figure out just what is going on, though it seems not all options work there.

**Comment by rkdarst** [comment]
Is this solved now?

**Comment by willingc** [comment]
I'm going to close this as resolved by unsetting XDG_RUNTIME_DIR
